// Generated by CoffeeScript 1.7.1
(function() {
  var http, server;

  http = require('http');

  server = http.createServer().listen(8080);

  server.on('request', function(request, response) {
    var callback, callbackName, options, querystring;
    querystring = require('url').parse(request.url, true);
    callbackName = querystring.query['callback'];
    options = {
      host: 'data.police.uk',
      path: '/api/crimes-street-dates'
    };
    callback = function(rsp) {
      response.write("" + callbackName + "(");
      rsp.on('data', function(chunk) {
        return response.write(chunk.toString());
      });
      return rsp.on('end', function() {
        return response.end(')');
      });
    };
    return http.request(options, callback).end();
  });

}).call(this);
